mqtt:
  host: 192.168.0.1
  port: 1883
  username: user
  password: pass
  #base_name: cam2mqtt
  ssl: false
  #required: true # leave it on true (default) to avoid losing messages on startup

webhook:
  external_url: http://192.168.0.1:8080 # only needed for webhook subscriptions

cameras:
  reolink_cam_1:
    host: 192.168.4.1
    username: admin
    password: somepass
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
        # motion_debounce: true
        # force_motion_debounce_time: 2 seconds # send motion=off after this time if camera does not report any other motion event
      reolink:
        # port: 443 # optional. 443/HTTPS by default
        # username: bob # optional. Alternative username for Reolink API
        # password: bobpass # optional. Alternative password for Reolink API
        # ssl: false # optional. Use ssl/HTTPS
        ai_detection_mode: off # one of [off, on_motion, continuous]. on_motion requires onvif module to detect motion
        sync_datetime: false
        # audio: false # allow to control audio alarm volume (can't be autodetected)
        # alarm: false # allow to control alarm siren (can't be autodetected)
        # spotlight: false # allow to control spotlight (can't be autodetected)
  onvif_cam_1:
    host: 192.168.4.2
    username: admin
    password: somepass
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
