mqtt:
  host: 192.168.0.1
  port: 1883
  username: user
  password: pass
  #base_name: cam2mqtt
  ssl: false

webhook:
  external_url: http://192.168.0.1:8080 # only needed for webhook subscriptions

cameras:
  reolink_cam_1:
    host: 192.168.4.1
    username: admin
    password: somepass
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        # port: 443 # optional. 443/HTTPS by default
        # username: bob # optional. Alternative username for Reolink API
        # password: bobpass # optional. Alternative password for Reolink API
        # ssl: false # optional. Use ssl/HTTPS
        sync_datetime: false
  onvif_cam_1:
    host: 192.168.4.2
    username: admin
    password: somepass
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
